version: '3.8'
services:
  api_service:
    build: ./api_service
    volumes:
      - ./common:/usr/src/app/common
    ports:
      - "8000:8000"
  chatbot_service:
    build: ./chatbot_service
    volumes:
      - ./common:/usr/src/app/common
    ports:
      - "8001:8000"
    depends_on:
      - api_service
